### ISSUE TITLE
docker host container could be moved from ubuntu to CoreOS

### ISSUE THREAD

**Issue by mccrackend** [Google-IO-Extended-Grand-Rapids/conference_web#12]
CoreOS is being touted as 'the docker host' and is not as large as ubuntu.  40% smaller memory footprint.  https://coreos.com/

**Comment by chenry** [comment]
@danmikita @mccrackend how strongly do you feel about this?

**Comment by danmikita** [comment]
@chenry I personally want to learn CoreOS still. But, I don't necessarily feel we HAVE to do this now. We can switch at any time, so we can close this if you want.

**Comment by chenry** [comment]
Closing.
