### ISSUE TITLE
DateTime's returned from API should be in ISO 8601 format

### ISSUE THREAD

**Issue by mccrackend** [Google-IO-Extended-Grand-Rapids/conference_web#18]
One thing we should try to address in a future PR is the outbound DateTime format.

eg. "startDate":"2012-04-23T18:25:43"
instead of: "startDate":1423344664458

[Source](http://stackoverflow.com/questions/10286204/the-right-json-date-format)

**Comment by chenry** [comment]
Here is a reference on how to handle this:

http://briansjavablog.blogspot.com/2012/08/rest-services-with-spring.html
