### ISSUE TITLE
Change the name of the artifact from gs-rest-service to conference-web

### ISSUE THREAD

**Issue by chenry** [Google-IO-Extended-Grand-Rapids/conference_web#4]
Let's change the name of the artifact from gs-rest-service to conference-web.  Along with this, there are various places that we will also need to change it:
- documentation
- vagrant / docker / property files

**Comment by will1771** [comment]
Starting: right now!
Projected finish: by tonight!

**Comment by will1771** [comment]
PR in.... is there a way to link the PR to the issue?

**Comment by chenry** [comment]
This fixed the issue.
