### ISSUE TITLE
Adding tables to support ROLES in the database

### ISSUE THREAD

**Issue by chenry** [Google-IO-Extended-Grand-Rapids/conference_web#45]
At this point, I am thinking that there are only two levels of security.  Administrators and everyone else.  Every user should at least have the one generic role.  We will select which user accounts has admin privileges.

**Comment by will1771** [comment]
Starting: now.

Hope to Finish: by end of tonight.

**Comment by will1771** [comment]
We are thinking a Roles tables, and then a user_roles many-to-many table to connect users and roles.
