### ISSUE TITLE
Tell me about the application-local.properties file

### ISSUE THREAD

**Issue by chenry** [Google-IO-Extended-Grand-Rapids/conference_web#6]
Why does the startup script specify an application-local.properties, but there is not one in the project?  Is this a file that I need?  If so, what should the contents be?

**Comment by mccrackend** [comment]
What startup script? And is this question relevant still?

**Comment by chenry** [comment]
I think that the question is only relevant to those that will be working on the web application and it goes to workflow.  In the _Procfile_, it says that the startup script should use _application-production.properties_.  My assumption is that this will have the production version of the application.properties file.

The _Dockerfile_ does not specify anything at all.  At one point and time, there was a mention of _application-local.properties_.  

It ultimately goes back to workflow.  What is the development workflow for
- iOS
- Android
- Web Application Developers

Thoughts?

**Comment by mccrackend** [comment]
The Procfile isn't being used at all in our current configuration!  I spoke with @danmikita about this and it's leftover stuff from heroku hosting I believe.

**Comment by chenry** [comment]
Doh. Red herring. Let's get rid of that file asap
