### ISSUE TITLE
Maven resource filtering for database properties

### ISSUE THREAD

**Issue by chenry** [Google-IO-Extended-Grand-Rapids/conference_web#8]
There are some properties that are being specified in many location for database connections.  These files should be 'maven filtered' such that depending on how the application is built or what profile is ran, these properties can be replaced with their appropriate values.

Files that should be filtered include:
- application.properties
- application-production.properties
- application-no-web.properties
- liquibase.properties

**Comment by mccrackend** [comment]
Agree, and I didn't help by adding a 5th config file called liquibase.travis.properties with PR #10.  Sorry.
