### ISSUE TITLE
Application will not start successfully - Database Connectivity Issues

### ISSUE THREAD

**Issue by chenry** [Google-IO-Extended-Grand-Rapids/conference_web#9]
...Yes, it is my fault, but I don't know how to fix it and I need some help.

In an effort to build the data model, I set my local environment up so that it would not start the web application.  Then I exposed the database to my local machine through the use of port forwarding.  Then in order to start the application, I ran the command of **mvn clean install && --spring.config.location=classpath:/application-no-web.properties**.  This command sets up the local database using a tool called liquibase.  It's main database configuration properties are located in a file called **liquibase.properties**

After merging that into develop, I attempted to start the application using both the db and web docker containers.  The db container starts up fine, but the web container is having problems connecting to the database.

I am not very well versed in docker, so any help to resolve this issue would be greatly appreciated.

**Comment by mccrackend** [comment]
@chenry gotta say something like "fixes #9" in a commit message in the PR - not just reference it in the comments :+1:

**Comment by chenry** [comment]
@mccrackend thanks for the tidbit
